version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "User ID=postgres;Password=gowthamm1@;Host=postgres;Port=5432;Database=ClinicApp1;"
      Keys__JwtTokenKey: "This is a summy key that is used for development. Ensure you replace this"
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gowthamm1@
      POSTGRES_DB: ClinicApp1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
